### ISSUE TITLE
WARNING: There is no atom named "OE2" in the protein residue GLU_646_A.

### ISSUE THREAD

**Issue by BlANK-0615** [durrantlab/binana#1]
Hello,

I am using BINANA2 to calculate the characteristics of pdbqt molecules after docking, but I get an error after running binana2.1: File "**mypath\_electrostatic_energies.py", line 54, in get_electrostatic_energies coulomb_energy = (ligand_charge * receptor_charge / dist) * 138.94238460104 697e4
ZeroDivisionError: float division by zero.**
Indicates that dist is not calculated.

At the same time, it is displayed in errors.txt: 
**WARNING: There is no atom named "OE2" in the protein residue GLU_646_A. Please use standard naming conventions for all protein residues to improve BINANA accuracy.**
I guess that's why dist is not being calculated, but what about the standard naming conventions? Both my receptors and ligands are pdbqt files generated by MGLtools.

Thank you so much for being able to answer my question.

**Comment by BlANK-0615** [comment]
Sorry, I think I know why the dist=0 error occurs, because when I use the command line, I also enter the path of the receptor after -ligand, so the distance between the two must be 0, please forgive me for this stupid mistake, very feel sorry !！

I then successfully ran BINANA2.1, but there are still warnings in the errors file:
**WARNING: There is no atom named "OE2" in the protein residue GLU_646_A. Please
use standard naming conventions for all protein residues to improve BINANA
accuracy.**

I think this problem should not be caused by wrong operation.

Many thanks，
Puxin

**Comment by jacobdurrant** [comment]
Hi Puxin,

Thanks for reaching out. No need to apologize for the confusion about the distance measurement. I'm glad to hear that you successfully resolved that issue!

Re. the atom-name warning, BINANA assumes the atoms in proteins are named according to the standard PDB convention. But, in some cases, certain residues may have missing atoms due to limitations in crystallographic resolution. This warning simply indicates that one of the residues in your protein did not have one of the expected atoms, either because it is missing or named in a non-standard way.

Unless you specifically need to analyze interactions involving that particular residue, it should be safe to ignore this warning. 

Thanks again for your interest in the software and for reaching out!
